FROM golang:1.23 as build

WORKDIR /app

COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cloudrun ./cmd/weather-zip-code

FROM scratch

WORKDIR /app

COPY --from=build /app/cloudrun .

COPY cmd/weather-zip-code/.env .

ENTRYPOINT ["./cloudrun"]